# Generated by Django 3.2.10 on 2021-12-09 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_district',
            name='division',
        ),
    ]
