# Generated by Django 3.2.10 on 2021-12-09 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_remove_sub_district_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristplaces',
            name='ratting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratting', to='places.ratting'),
        ),
    ]
