# Generated by Django 3.2.10 on 2021-12-10 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_famousfood_hotels_nearestplace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='famousfood',
            name='district',
        ),
        migrations.RemoveField(
            model_name='hotels',
            name='district',
        ),
        migrations.RemoveField(
            model_name='nearestplace',
            name='district',
        ),
        migrations.AddField(
            model_name='famousfood',
            name='sub_district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.sub_district'),
        ),
        migrations.AddField(
            model_name='hotels',
            name='sub_district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.sub_district'),
        ),
        migrations.AddField(
            model_name='nearestplace',
            name='sub_district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.sub_district'),
        ),
    ]
