# Generated by Django 3.2.10 on 2021-12-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_auto_20211211_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristplaces',
            name='price',
            field=models.IntegerField(default=200),
        ),
    ]
