# Generated by Django 3.2.7 on 2021-12-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_touristplaces_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='map_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
