# Generated by Django 3.2.7 on 2021-12-14 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_district_map_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='map_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
