# Generated by Django 3.2.7 on 2021-12-15 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0008_alter_district_map_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('person', models.IntegerField(default=2)),
                ('ordered', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now=True)),
                ('transaction_id', models.CharField(default='', max_length=500)),
                ('ammount', models.FloatField(default=0.0, max_length=100)),
                ('card_type', models.CharField(default='', max_length=100)),
                ('payment_status', models.CharField(default='', max_length=100)),
                ('transaction_date', models.CharField(default='', max_length=100)),
                ('risk_title', models.CharField(default='', max_length=100)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='places.touristplaces')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
