# Generated by Django 3.2.10 on 2021-12-18 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_placeorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topratedplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.CharField(max_length=200)),
                ('description', models.TextField(default='Description text will be added here')),
                ('image', models.ImageField(upload_to='Top Rated/')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.district')),
                ('division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.division')),
                ('sub_district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.sub_district')),
            ],
        ),
    ]
