# Generated by Django 3.2.10 on 2021-12-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0011_topratedplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='topratedplace',
            name='price',
            field=models.IntegerField(default=1500),
        ),
    ]
