# Generated by Django 3.2.10 on 2021-12-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0013_topplaceorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='topplaceorder',
            name='person',
            field=models.IntegerField(default=2),
        ),
    ]
