# Generated by Django 3.2.10 on 2021-12-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0015_auto_20211220_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topplaceorder',
            name='card_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='topplaceorder',
            name='payment_status',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='topplaceorder',
            name='risk_title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='topplaceorder',
            name='transaction_date',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
