from django.urls import path
from .views import *

urlpatterns = [
    path('', homePage,name='home' ),
    path('places/',search_view,name='search_place'),
    path('places/details/<int:id>',place_details,name='place_details'),
    path('single-place/<int:id>',single_place,name='single_place'),
    path('add-rating', AddRating, name="add_rating"),
    path('place-requriement/<int:id>',place_requriement,name='place_requriementfile'),
    path('place-success/', place_success,name='place_success'),
    path('place-failed/', place_failed,name='place_failed'),
    path('place-cancel/', place_cancel,name='place_cancel'),
    path('place-status/', place_payment_status,name='place_payment_status'),
    path('toprated-place/<int:id>', topdatedplacedetails,name='toprateplace_details'),
    path('pay/<int:id>', payment, name="payment"),
    path('status/', complete, name="complete"),
    path('purchase/<val_id>/<tran_id>/', purchase, name="purchase"),
    path('completepurchase-place/<val_id>/<tran_id>/', completepurchase, name="completepurchase_place"),
    path('guider-list/', guider_view, name="guider_view"),
    path('guider-details/<int:id>', guider_details, name="guider_details"),
    path('guider-ratting/', guider_ratting, name="guider_ratting"),
    path('guider-pay/<int:id>', guider_payment, name="guider_payment"),
    path('guider-complete', guider_complete, name="guider_complete"),
    path('guider-complete-purchased/<val_id>/<tran_id>/', guidercompletepurchase, name="guidercompletepurchase"),
    path('feedback',feedbackview,name='feedback'),
    path('gallery',galleryview,name='gallery'),
    path('love/<int:id>', love_view, name="love_view"),
    path('even-love/<int:id>', love_view_event, name="love_view_event"),
    path('fag-page',Faq_view,name='faq'),
    path('about-us',Aboutus_view,name='about'),
    path('contact-us',Contractus_view,name='contact'),
    path('trams-condition',Conditions_view,name='condition'),
    path('how-to-use',Howtouse_view,name='howtouse'),
    path('join-email',join_email_view,name='join_email'),
    path('destination',destination_view,name='destination_view'),
]