# Generated by Django 3.2.10 on 2021-12-20 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0002_alter_guider_ratting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guider',
            name='ratting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='guider_ratting', to='tourist.ratting'),
        ),
    ]
