# Generated by Django 3.2.10 on 2021-12-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0008_feedback_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='image',
            field=models.ImageField(blank=True, upload_to='feedback/'),
        ),
    ]
