# Generated by Django 3.2.8 on 2021-10-23 19:36

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TransportService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserTouristEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=500)),
                ('slug', models.SlugField(blank=True, max_length=300, null=True)),
                ('event_Description', ckeditor.fields.RichTextField()),
                ('traveling_dates', models.DateField(null=True)),
                ('total_traveling_person', models.IntegerField()),
                ('traveller_location', models.CharField(max_length=500)),
                ('guider_confirmation', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='Yes', max_length=100)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('transport_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.transportservice')),
                ('traveller_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.destination')),
            ],
        ),
        migrations.CreateModel(
            name='AdminTouristEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=500)),
                ('slug', models.SlugField(blank=True, max_length=300, null=True)),
                ('event_description', ckeditor.fields.RichTextField()),
                ('traveling_dates', models.DateField(null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
