# Generated by Django 3.2.8 on 2021-10-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20211024_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='admintouristevent',
            name='traveling_location',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
