# Generated by Django 3.2.8 on 2021-10-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_admintouristevent_traveling_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=500)),
                ('ammount', models.FloatField(max_length=100)),
                ('card_type', models.CharField(max_length=100)),
                ('payment_status', models.CharField(max_length=100)),
                ('transaction_date', models.CharField(max_length=100)),
                ('risk_title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='admintouristevent',
            name='event_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='usertouristevent',
            name='guider_confirmation',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='Yes', max_length=100),
        ),
    ]
