# Generated by Django 3.2.8 on 2021-10-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20211024_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertouristevent',
            name='event_image',
            field=models.ImageField(null=True, upload_to='User_Event/images/'),
        ),
        migrations.AlterField(
            model_name='admintouristevent',
            name='event_image',
            field=models.ImageField(null=True, upload_to='Admin_Event/images/'),
        ),
    ]
