# Generated by Django 3.2.8 on 2021-10-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20211026_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertouristevent',
            name='event_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='usertouristevent',
            name='guider_confirmation',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=100),
        ),
    ]
