# Generated by Django 3.2.8 on 2021-10-25 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20211026_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='admintouristevent',
            name='guider_confirmation',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=100),
        ),
        migrations.AddField(
            model_name='admintouristevent',
            name='transport_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.transportservice'),
        ),
    ]
