# Generated by Django 3.2.10 on 2021-12-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_auto_20211209_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admintouristevent',
            name='publish',
            field=models.CharField(choices=[('Reject', 'Reject'), ('Accept', 'Accept'), ('Pending', 'Pending')], default='Pending', max_length=100),
        ),
    ]
