# Generated by Django 3.2.7 on 2021-12-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0019_auto_20211211_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admintouristevent',
            name='publish',
            field=models.CharField(choices=[('Reject', 'Reject'), ('Accept', 'Accept'), ('Pending', 'Pending')], default='Pending', max_length=100),
        ),
    ]
