# Generated by Django 3.2.7 on 2021-12-15 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0024_auto_20211215_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admintouristevent',
            name='publish',
            field=models.CharField(choices=[('Reject', 'Reject'), ('Accept', 'Accept'), ('Pending', 'Pending')], default='Pending', max_length=100),
        ),
    ]
