# Generated by Django 3.2.10 on 2021-12-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0035_auto_20211220_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admintouristevent',
            name='publish',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Reject', 'Reject'), ('Accept', 'Accept')], default='Pending', max_length=100),
        ),
    ]
